export default {
  pages: ['pages/home/main/index'],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
  subpackages: [
    {
      root: 'example',
      name: '组件示例',
      pages: [
        'pages/ellipsis/index',
        'pages/price/index',
        'pages/colorText/index',
        'pages/imageBox/index',
        'pages/avatar/index',
        'pages/badge/index',
        'pages/noticeBar/index',
        'pages/layout/index',
        'pages/steps/index',
        'pages/advanceButton/index',
        'pages/divider/index',
        'pages/tag/index',
        'pages/advanceInput/index',
        'pages/stepper/index',
        'pages/stepperItem/index',
        'pages/button/index',
        'pages/advanceSwitch/index',
        'pages/advanceProgress/index',
        'pages/advanceProgressBox/index',
        'pages/notification/index',
        'pages/grid/index',
        'pages/selector/index',
        'pages/tabs/index',
        'pages/transition/index',
        'pages/card/index',
        'pages/item/index',
        'pages/overlay/index',
        'pages/popup/index',
        'pages/circle/index',
        'pages/swiper/index',
        'pages/radio/index',
        'pages/radioSelector/index',
        'pages/checkBox/index',
        'pages/checkBoxSelector/index',
        'pages/countdown/index',
        'pages/helpBox/index',
        'pages/copyright/index',
        'pages/floatAction/index',
        'pages/verticalBox/index',
        'pages/horizontalCenterBox/index',
        'pages/flexBox/index',
        'pages/centerBox/index',
        'pages/dataGrid/index',
        'pages/searchBar/index',
      ],
    },
  ],
};
