// eslint-disable-next-line no-undef
export default defineAppConfig({
  entryPagePath: 'pages/entry/main/index',
  pages: [
    'pages/user/main/index',
    'pages/entry/main/index',
    'pages/flowCase/main/index',
    'pages/home/main/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'white',
  },
  subpackages: [
    {
      root: 'information',
      name: '信息',
      pages: [
        'pages/pageListNotice/main/index',
        'pages/noticeDetail/main/index',
      ],
    },
    {
      root: 'communication',
      name: '通讯',
      pages: ['pages/singleListAddressBook/main/index'],
    },
    {
      root: 'webPage',
      name: '网页',
      pages: ['pages/general/main/index'],
    },
    {
      root: 'user',
      name: 'User',
      pages: [
        'pages/approve/main/index',
        'pages/changePassword/main/index',
        'pages/detailFlowCase/main/index',
        'pages/editInformation/main/index',
        'pages/flowCaseForm/main/index',
        'pages/pageListCreateApprove/main/index',
        'pages/pageListLatestApprove/main/index',
        'pages/pageListWaitApprove/main/index',
        'pages/pageListWorkflow/main/index',
        'pages/resetPassword/main/index',
        'pages/security/main/index',
        'pages/setAddress/main/index',
        'pages/setAvatar/main/index',
        'pages/setBirthday/main/index',
        'pages/setting/main/index',
        'pages/signIn/main/index',
        'pages/signInWithWeChat/main/index',
      ],
    },
    {
      root: 'suggestion',
      name: '投诉建议',
      pages: [
        'pages/customer/main/index',
        'pages/detailComplaint/main/index',
        'pages/detailFeedback/main/index',
        'pages/detailReport/main/index',
        'pages/editInformation/main/index',
        'pages/home/main/index',
        'pages/illustrate/main/index',
        'pages/pageListComplaint/main/index',
        'pages/pageListFeedback/main/index',
        'pages/pageListReport/main/index',
        'pages/resetPassword/main/index',
        'pages/setAvatar/main/index',
        'pages/signIn/main/index',
        'pages/signInWithWeChat/main/index',
        'pages/submitComplaint/main/index',
        'pages/submitFeedback/main/index',
        'pages/submitReport/main/index',
        'pages/verifyPhone/main/index',
      ],
    },
  ],
  preloadRule: {
    'pages/entry/main/index': {
      network: 'all',
      packages: ['information', 'communication', 'user', 'suggestion'],
    },
  },
  // permission: {
  //   'scope.userLocation': {
  //     desc: '你的位置信息将用于显示当地天气等信息。',
  //   },
  // },
  // requiredPrivateInfos: [
  //   'getFuzzyLocation',
  //   'onLocationChange',
  //   'chooseAddress',
  //   'choosePoi',
  //   'chooseLocation',
  //   'startLocationUpdate',
  // ],
  requiredPrivateInfos: [],
  serviceProviderTicket: '',
  tabBar: {
    color: '#353535',
    selectedColor: '#3778F4',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/main/index',
        iconPath: './assets/tab-bar/workbench.png',
        selectedIconPath: './assets/tab-bar/workbench-active.png',
        text: '工作台',
      },
      {
        pagePath: 'pages/flowCase/main/index',
        iconPath: './assets/tab-bar/approve.png',
        selectedIconPath: './assets/tab-bar/approve_active.png',
        text: '审批',
      },
      // {
      //   pagePath: 'pages/workbench/main/index',
      //   iconPath: './assets/tab-bar/workbench.png',
      //   selectedIconPath: './assets/tab-bar/workbench-active.png',
      //   text: '工作台',
      // },
      // {
      //   pagePath: 'pages/contact/main/index',
      //   iconPath: './assets/tab-bar/news.png',
      //   selectedIconPath: './assets/tab-bar/news-active.png',
      //   text: '通讯录',
      // },
      {
        pagePath: 'pages/user/main/index',
        iconPath: './assets/tab-bar/user.png',
        selectedIconPath: './assets/tab-bar/user-active.png',
        text: '我的',
      },
    ],
  },
  // lazyCodeLoading: 'requiredComponents',
});
